/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GVJ.gui;

import java.awt.Color;
import java.util.Arrays;
import java.util.List;

import javax.swing.ComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JTextField;

import org.biojava.nbio.core.sequence.DNASequence;
import org.biojava.nbio.genome.parsers.gff.FeatureList;
import org.checkerframework.checker.units.qual.t;

import GVJ.models.DataManager;
import static GVJ.utils.FastaUtils.getSequenceLength;
import static GVJ.utils.FastaUtils.getSequenceGCcount;
import static GVJ.utils.FastaUtils.sequencesGetAverageLength;
import static GVJ.utils.FastaUtils.bp2Mbp;

import static GVJ.utils.GffUtils.getAllGeneIds;
import static GVJ.utils.GffUtils.countFeaturesAccrossAllGenes;
import static GVJ.utils.GffUtils.countFeaturesInGene;
import static GVJ.utils.GffUtils.longestFeature;
import static GVJ.utils.GffUtils.shortestFeature;
import static GVJ.utils.GffUtils.averageFeatureLength;
import static GVJ.utils.GffUtils.getGeneLength;

import java.util.Map;

/**
 *
 * @author mspriggs
 */
public class basicStatistics extends javax.swing.JPanel {

        private DataManager dataManager;

        /**
         * Creates new form basicStatistics
         */
        public basicStatistics() {
                initComponents();

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jTabbedPane1 = new javax.swing.JTabbedPane();
                jPanel1 = new javax.swing.JPanel();
                jLabelTotalSeqLen = new javax.swing.JLabel();
                jLabelNumSeq = new javax.swing.JLabel();
                jLabelAvgSeqLen = new javax.swing.JLabel();
                jLabelGCcont = new javax.swing.JLabel();
                jTextFieldTotalSeqLen = new javax.swing.JTextField();
                jTextFieldNumSeq = new javax.swing.JTextField();
                jTextFieldAvgSeqLen = new javax.swing.JTextField();
                jTextFieldGCcont = new javax.swing.JTextField();
                jPanel2 = new javax.swing.JPanel();
                jLabelSelectGene = new javax.swing.JLabel();
                jComboBoxSelectGene = new javax.swing.JComboBox<>();
                jLabelgetFeature = new javax.swing.JLabel();
                jComboBoxgetFeature = new javax.swing.JComboBox<>();
                jLabelAvgNumByGene = new javax.swing.JLabel();
                jTextFieldAvgNumByGene = new javax.swing.JTextField();
                jLabelLongestFeature = new javax.swing.JLabel();
                jTextFieldLongestFeature = new javax.swing.JTextField();
                jLabelAvgFeatureLength = new javax.swing.JLabel();
                jTextFieldAvgFeatureLength = new javax.swing.JTextField();
                jButtonUpdate = new javax.swing.JButton();
                jLabelShortestFeature = new javax.swing.JLabel();
                jTextFieldShortestFeature = new javax.swing.JTextField();

                jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
                        public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                jTabbedPane1StateChanged(evt);
                        }
                });

                jLabelTotalSeqLen.setText("Total Sequence Length (Mbp):");

                jLabelNumSeq.setText("Number of Sequences:");

                jLabelAvgSeqLen.setText("Average Sequence Length (Mbp):");

                jLabelGCcont.setText("GC Count:");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(32, 32, 32)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabelTotalSeqLen)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(3, 3, 3)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabelAvgSeqLen)
                                                                                                                .addComponent(jLabelGCcont)
                                                                                                                .addComponent(jLabelNumSeq))))
                                                                .addGap(38, 38, 38)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jTextFieldNumSeq,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                199,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jTextFieldTotalSeqLen,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                199,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jTextFieldAvgSeqLen,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                199,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jTextFieldGCcont,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                199,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(54, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(41, 41, 41)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabelTotalSeqLen)
                                                                                .addComponent(jTextFieldTotalSeqLen,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(21, 21, 21)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabelNumSeq)
                                                                                .addComponent(jTextFieldNumSeq,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(28, 28, 28)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabelAvgSeqLen)
                                                                                .addComponent(jTextFieldAvgSeqLen,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(21, 21, 21)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabelGCcont)
                                                                                .addComponent(jTextFieldGCcont,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(76, Short.MAX_VALUE)));

                jTabbedPane1.addTab("FASTA", jPanel1);

                jLabelSelectGene.setText("Select Gene:");

                jComboBoxSelectGene.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                jLabelgetFeature.setText("Select Feature:");

                jComboBoxgetFeature.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                jLabelAvgNumByGene.setText("Average Number of Features:");

                jTextFieldAvgNumByGene.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldAvgNumByGeneActionPerformed(evt);
                        }
                });

                jLabelLongestFeature.setText("Longest Feature:");

                jLabelAvgFeatureLength.setText("Average Gene Length:");

                jButtonUpdate.setText("Update");
                jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonUpdateActionPerformed(evt);
                        }
                });

                jLabelShortestFeature.setText("Shortest Feautre:");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabelSelectGene)
                                                                                .addComponent(jComboBoxSelectGene,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jComboBoxgetFeature,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabelgetFeature)
                                                                                .addComponent(jButtonUpdate))
                                                                .addGap(40, 40, 40)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jLabelAvgFeatureLength)
                                                                                .addComponent(jLabelLongestFeature)
                                                                                .addComponent(jLabelAvgNumByGene)
                                                                                .addComponent(jTextFieldAvgNumByGene,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                237, Short.MAX_VALUE)
                                                                                .addComponent(jTextFieldLongestFeature)
                                                                                .addComponent(jTextFieldAvgFeatureLength)
                                                                                .addComponent(jLabelShortestFeature)
                                                                                .addComponent(jTextFieldShortestFeature))
                                                                .addContainerGap(126, Short.MAX_VALUE)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(22, 22, 22)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabelSelectGene)
                                                                                .addComponent(jLabelAvgNumByGene))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jComboBoxSelectGene,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jTextFieldAvgNumByGene,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabelgetFeature)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jComboBoxgetFeature,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabelLongestFeature)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jTextFieldLongestFeature,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(27, 27, 27)
                                                                                                .addComponent(jButtonUpdate))
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabelShortestFeature)
                                                                                                .addGap(1, 1, 1)
                                                                                                .addComponent(jTextFieldShortestFeature,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(17, 17, 17)
                                                                .addComponent(jLabelAvgFeatureLength)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jTextFieldAvgFeatureLength,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(19, Short.MAX_VALUE)));

                jTabbedPane1.addTab("Features", jPanel2);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jTabbedPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                519,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(89, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jTabbedPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                314,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(63, Short.MAX_VALUE)));
        }// </editor-fold>//GEN-END:initComponents

        private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_jTabbedPane1StateChanged
                int selectedIndex = jTabbedPane1.getSelectedIndex();
                if (selectedIndex == 1) { // FASTA Statistics tab
                        refreshFASTAStats();
                } else if (selectedIndex == 2) { // GFF Statistics tab
                        refreshComboBoxs();
                }
        }// GEN-LAST:event_jTabbedPane1StateChanged

        private void jTextFieldAvgNumByGeneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldAvgNumByGeneActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextFieldAvgNumByGeneActionPerformed

        private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonUpdateActionPerformed
                // get selected gene and feature
                String selectedGene = (String) jComboBoxSelectGene.getSelectedItem();
                String selectedFeature = (String) jComboBoxgetFeature.getSelectedItem();

                // update jTextFieldAvgNumByGene
                setAvgNumByGene(selectedGene, selectedFeature);

                // update jTextFieldLongestFeature
                setLongestFeature(selectedGene, selectedFeature);

                // update jTextFieldShortestFeature
                setShortestFeature(selectedGene, selectedFeature);

                // update jTextFieldAvgFeatureLength
                setAvgFeatureLength(selectedGene, selectedFeature);

        }// GEN-LAST:event_jButtonUpdateActionPerformed

        public void setDataManager(DataManager dataManager) {
                this.dataManager = dataManager;
        }

        // could be 2 methods to refresh each combobox separately
        // not very specific, relates to GFF combo boxes for future reference
        public void refreshComboBoxs() {

                // Refresh Gene Selector ComboBox
                jComboBoxSelectGene.removeAllItems(); // Clear existing items

                // Get all gene IDs from GFF data
                FeatureList gff = dataManager.getGffData();
                List<String> geneIds = getAllGeneIds(gff);

                // Append "Select All" option at the beginning
                geneIds.add(0, "Select All");

                jComboBoxSelectGene.setEditable(true); // Make it editable for typing
                for (String geneId : geneIds) {
                        jComboBoxSelectGene.addItem(geneId);
                }

                // Refresh Feature Selector ComboBox
                // TODO make this dynamic based on GFF content: Add to tech debt log

                List<String> featureTypes = Arrays.asList("gene", "mRNA", "intron", "exon", "CDS");
                jComboBoxgetFeature.removeAllItems(); // Clear existing items
                jComboBoxgetFeature.setEditable(true); // Make it editable for typing search
                for (String featureType : featureTypes) {
                        jComboBoxgetFeature.addItem(featureType);
                }
        }

        public void refreshFASTAStats() {
                // Calculate and display FASTA statistics
                // update total sequence length
                updateTotalSeqLen();

                // update number of sequences
                updateNumSeq();

                // update average sequence length
                updateAvgSeqLen();

                // update GC content
                updateGCcontent();
        }

        private void setAvgNumByGene(String selectedGene, String selectedFeature) {
                try {

                        restsTextField(jTextFieldAvgNumByGene, jLabelAvgNumByGene);

                        FeatureList gff = dataManager.getGffData();
                        if (selectedGene.equals("Select All")) {

                                // calculate average number of features per gene across all genes
                                double avgNumFeaturesPerGene = countFeaturesAccrossAllGenes(gff, selectedFeature);
                                jTextFieldAvgNumByGene.setText(String.format("%.2f", avgNumFeaturesPerGene));

                                // update jLabelAvgNumByGene to reflect "all genes"
                                jLabelAvgNumByGene.setText("Average Number of " + selectedFeature + "s per all genes:");
                        } else {
                                double avgNumFeaturesPerGene = countFeaturesInGene(gff, selectedFeature, selectedGene);
                                jTextFieldAvgNumByGene.setText(String.format("%.2f", avgNumFeaturesPerGene));

                                // update jLabelAvgNumByGene to reflect selected gene
                                jLabelAvgNumByGene
                                                .setText("Number of " + selectedFeature + "s in " + selectedGene + ":");
                        }
                } catch (NullPointerException e) {
                        cannotComputeTextField(jTextFieldAvgNumByGene, jLabelAvgNumByGene);

                }
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonUpdate;
        private javax.swing.JComboBox<String> jComboBoxSelectGene;
        private javax.swing.JComboBox<String> jComboBoxgetFeature;
        private javax.swing.JLabel jLabelAvgFeatureLength;
        private javax.swing.JLabel jLabelAvgNumByGene;
        private javax.swing.JLabel jLabelAvgSeqLen;
        private javax.swing.JLabel jLabelGCcont;
        private javax.swing.JLabel jLabelLongestFeature;
        private javax.swing.JLabel jLabelNumSeq;
        private javax.swing.JLabel jLabelSelectGene;
        private javax.swing.JLabel jLabelShortestFeature;
        private javax.swing.JLabel jLabelTotalSeqLen;
        private javax.swing.JLabel jLabelgetFeature;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTextField jTextFieldAvgFeatureLength;
        private javax.swing.JTextField jTextFieldAvgNumByGene;
        private javax.swing.JTextField jTextFieldAvgSeqLen;
        private javax.swing.JTextField jTextFieldGCcont;
        private javax.swing.JTextField jTextFieldLongestFeature;
        private javax.swing.JTextField jTextFieldNumSeq;
        private javax.swing.JTextField jTextFieldShortestFeature;
        private javax.swing.JTextField jTextFieldTotalSeqLen;
        // End of variables declaration//GEN-END:variables

        private void setLongestFeature(String selectedGene, String selectedFeature) {
                try {
                        FeatureList gff = dataManager.getGffData();
                        if (selectedGene.equals("Select All")) {
                                // rests label color in case it was set to red previously
                                jLabelLongestFeature.setForeground(Color.BLACK);

                                // calculate longest feature across all genes
                                int longestFeatureLength = longestFeature(gff, selectedFeature);
                                jTextFieldLongestFeature.setText(Integer.toString(longestFeatureLength));

                                // update jLabelAvgNumByGene to reflect "all genes"
                                jLabelLongestFeature.setText("Longest " + selectedFeature + " across all genes:");

                        } else {
                                // calculate longest feature in selected gene
                                int longestFeatureLength = longestFeature(gff, selectedFeature, selectedGene);
                                jTextFieldLongestFeature.setText(Integer.toString(longestFeatureLength));

                                // update jLabelAvgNumByGene to reflect selected gene
                                jLabelLongestFeature.setText(
                                                "Longest " + selectedFeature + " in " + selectedGene + ":");
                        }

                } catch (NullPointerException e) {
                        cannotComputeTextField(jTextFieldLongestFeature, jLabelLongestFeature);
                }
        }

        private void setShortestFeature(String selectedGene, String selectedFeature) {
                try {
                        restsTextField(jTextFieldShortestFeature, jLabelShortestFeature);

                        FeatureList gff = dataManager.getGffData();
                        if (selectedGene.equals("Select All")) {

                                // calculate shortest feature across all genes
                                int shortestFeatureLength = shortestFeature(gff, selectedFeature);
                                jTextFieldShortestFeature.setText(Integer.toString(shortestFeatureLength));

                                // update jLabelAvgNumByGene to reflect "all genes"
                                jLabelShortestFeature.setText("Shortest " + selectedFeature + " across all genes:");

                        } else {
                                // calculate shortest feature in selected gene
                                int shortestFeatureLength = shortestFeature(gff, selectedFeature, selectedGene);
                                jTextFieldShortestFeature.setText(Integer.toString(shortestFeatureLength));

                                // update jLabelAvgNumByGene to reflect selected gene
                                jLabelShortestFeature.setText(
                                                "Shortest " + selectedFeature + " in " + selectedGene + ":");
                        }

                } catch (NullPointerException e) {
                        cannotComputeTextField(jTextFieldShortestFeature, jLabelShortestFeature);
                }
        }

        private void setAvgFeatureLength(String selectedGene, String selectedFeature) {
                try {
                        restsTextField(jTextFieldAvgFeatureLength, jLabelAvgFeatureLength);

                        FeatureList gff = dataManager.getGffData();
                        if (selectedGene.equals("Select All")) {

                                // calculate average feature length across all genes
                                double avgLength = averageFeatureLength(gff, selectedFeature);
                                jTextFieldAvgFeatureLength.setText(String.format("%.2f", avgLength));

                                // update jLabelAvgNumByGene to reflect "all genes"
                                jLabelAvgFeatureLength
                                                .setText("Average " + selectedFeature + " Length across all genes:");
                        } else {
                                // calculate average feature length in selected gene
                                double length = getGeneLength(gff, selectedFeature, selectedGene);
                                jTextFieldAvgFeatureLength.setText(String.format("%.2f", length));

                                // update jLabelAvgNumByGene to reflect selected gene
                                jLabelAvgFeatureLength.setText(
                                                "Average " + selectedFeature + " Length in " + selectedGene + ":");
                        }

                } catch (NullPointerException e) {
                        cannotComputeTextField(jTextFieldAvgFeatureLength, jLabelAvgFeatureLength);
                }

        }

        private void cannotComputeTextField(JTextField jTextField, JLabel jLabel) {
                // TODO Auto-generated method stub
                jTextField.setText("N/A");
                jLabel.setText("Value could not be calculated");
                jLabel.setForeground(Color.RED);
        }

        private void restsTextField(JTextField jTextField, JLabel jLabel) {
                // TODO Auto-generated method stub
                jTextField.setText("");
                jLabel.setForeground(Color.BLACK);
        }

        private void updateTotalSeqLen() {
                Map<String, DNASequence> sequences = dataManager.getFastaData();

                int totalLen = 0;
                for (DNASequence sequence : sequences.values()) {
                        int seqLen = getSequenceLength(sequence);
                        System.out.println("Sequence Length: " + seqLen); // Debugging line
                        totalLen += seqLen;
                }

                double totalLenMbs = bp2Mbp((double) totalLen);
                jTextFieldTotalSeqLen.setText(Double.toString(totalLenMbs));

        }

        private void updateNumSeq() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                               // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private void updateAvgSeqLen() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                               // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private void updateGCcontent() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                               // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

}
