/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GVJ.gui;

import GVJ.models.DataManager;

import java.util.List;
import java.util.Map;

import javax.swing.JOptionPane;

import org.biojava.nbio.core.sequence.DNASequence;
import org.biojava.nbio.genome.parsers.gff.FeatureList;

import static GVJ.utils.FastaUtils.getSequenceIdentifiers;
import static GVJ.utils.GffUtils.getAllGeneIds;
import static GVJ.utils.GffUtils.getCoordsForGene;
import static GVJ.utils.GffUtils.getSequenceIdentifierfromGene;

import GVJ.models.DataManager;

/**
 *
 * @author mspriggs
 */
public class fastaVisualization extends javax.swing.JPanel {

    private DataManager dataManager;

    /**
     * Creates new form fastaVisualization
     */
    public fastaVisualization() {
        initComponents();
    }

    // Set DataManager

    public void setDataManager(DataManager dataManager) {
        this.dataManager = dataManager;
    }

    // refreshComboBoxes method - #TODO split into smaller methods.
    public void refreshComboBoxes() {

        /*
         * Update FASTA Sequence Names
         */
        // Clear existing items
        jComboBoxSelectGene.removeAllItems();
        jComboBoxSelectFeature.removeAllItems();

        /*
         * Update Gene Names from GFF Data
         */
        // Refresh Gene Selector ComboBox

        // Get all gene IDs from GFF data
        FeatureList gff = dataManager.getGffData();
        List<String> geneIds = getAllGeneIds(gff);

        for (String geneId : geneIds) {
            jComboBoxSelectGene.addItem(geneId);
        }

        /*
         * Update Feature Types from hardcoded list #TODO dynamic from GFF
         */
        List<String> featureTypes = List.of("mRNA", "intron", "exon", "CDS");
        for (String featureType : featureTypes) {
            jComboBoxSelectFeature.addItem(featureType);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaFastaDisplay = new javax.swing.JTextArea();
        jLabelSelectGene = new javax.swing.JLabel();
        jComboBoxSelectGene = new javax.swing.JComboBox<>();
        jLabelSelectFeature = new javax.swing.JLabel();
        jComboBoxSelectFeature = new javax.swing.JComboBox<>();
        jButtonUpdate = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FASTA Visualization",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jTextAreaFastaDisplay.setColumns(20);
        jTextAreaFastaDisplay.setLineWrap(true);
        jTextAreaFastaDisplay.setRows(5);
        jTextAreaFastaDisplay.setToolTipText("");
        jScrollPane1.setViewportView(jTextAreaFastaDisplay);

        jLabelSelectGene.setText("Select Gene:");

        jComboBoxSelectGene.setEditable(true);
        jComboBoxSelectGene.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelSelectFeature.setText("Select Feature:");

        jComboBoxSelectFeature.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelSelectGene,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 126,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jComboBoxSelectGene,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 187,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelSelectFeature,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 115,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jComboBoxSelectFeature,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 187,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(58, 58, 58)
                                                                .addComponent(jButtonUpdate,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 87,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabelSelectFeature)
                                                .addGap(5, 5, 5)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jComboBoxSelectFeature,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonUpdate)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabelSelectGene)
                                                .addGap(5, 5, 5)
                                                .addComponent(jComboBoxSelectGene,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(55, 55, 55)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(53, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {

        // Update FASTA DisplayBox
        updateFastaDisplay();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxSelectFeature;
    private javax.swing.JComboBox<String> jComboBoxSelectGene;
    private javax.swing.JLabel jLabelSelectFeature;
    private javax.swing.JLabel jLabelSelectGene;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaFastaDisplay;
    // End of variables declaration//GEN-END:variables

    private void updateFastaDisplay() {
        // get selected gene and feature
        String selectedGene = (String) jComboBoxSelectGene.getSelectedItem();

        // verify selectedGene
        // Get all gene IDs from GFF data
        FeatureList gff = dataManager.getGffData();

        List<String> geneIds = getAllGeneIds(gff);

        if (!selectedGene.equals("Select All") && !geneIds.contains(selectedGene)) {
            JOptionPane.showMessageDialog(this,
                    "Selected gene '" + selectedGene + "' not found in GFF data.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // get coordinates from GFF for selected gene
        int[] coords = getCoordsForGene(gff, selectedGene);
        int start = coords[0];
        int end = coords[1];

        // get sequence inferred from selected feature
        String seqKey = getSequenceIdentifierfromGene(gff, selectedGene);
        System.out.println("Sequence Key: " + seqKey);
        System.out.println("Selected Gene: " + selectedGene);

        // Upudate display area
        Map<String, DNASequence> fastaMap = dataManager.getFastaData();
        DNASequence dnaSequence = fastaMap.get(seqKey);
        String fullSequence = dnaSequence.getSequenceAsString();
        String substring = fullSequence.substring(start, end); // Adjust for 0-based index

        jTextAreaFastaDisplay.setText(substring);
    }
}
