/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GVJ.gui;

import GVJ.io.FastaParser;
import GVJ.io.GffParser;

import java.awt.Color;
import java.awt.FileDialog;
import java.awt.Frame;
import java.awt.Window;
import java.io.FilenameFilter;
import java.util.Map;
import java.io.File;
import javax.swing.JLabel;

import javax.swing.SwingUtilities;
import org.biojava.nbio.core.sequence.DNASequence;
import org.biojava.nbio.genome.parsers.gff.FeatureList;

import GVJ.models.DataManager;

/**
 *
 * @author mspriggs
 */
public class fileLoadPanel extends javax.swing.JPanel {

    private DataManager dataManager;

    /**
     * Creates new form fileLoadPanel
     */
    public fileLoadPanel() {
        initComponents();

        jLabelFastaFileStatus.setVisible(false);
        jLabelGffFileStatus.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroupFileSelection = new javax.swing.ButtonGroup();
        fileLoadInnerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonFASTA = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonGFF = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonLoad = new javax.swing.JButton();
        jButtonClearAllFiles = new javax.swing.JButton();
        jLabelFastaFileStatus = new javax.swing.JLabel();
        jLabelGffFileStatus = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        fileLoadInnerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "File Selection",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel2.setText("Choose a file type to load:");

        buttonGroupFileSelection.add(jRadioButtonFASTA);
        jRadioButtonFASTA.setText("FASTA");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 11)); // NOI18N
        jLabel3.setText("(.fa, .fasta)");

        buttonGroupFileSelection.add(jRadioButtonGFF);
        jRadioButtonGFF.setText("GFF");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 11)); // NOI18N
        jLabel4.setText("(.gff)");

        jButtonLoad.setText("Load");
        jButtonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadActionPerformed(evt);
            }
        });

        jButtonClearAllFiles.setText("Clear all");
        jButtonClearAllFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearAllFilesActionPerformed(evt);
            }
        });

        jLabelFastaFileStatus.setText("Loaded FASTA...");

        jLabelGffFileStatus.setText("Loaded GFF...");

        javax.swing.GroupLayout fileLoadInnerPanelLayout = new javax.swing.GroupLayout(fileLoadInnerPanel);
        fileLoadInnerPanel.setLayout(fileLoadInnerPanelLayout);
        fileLoadInnerPanelLayout.setHorizontalGroup(
                fileLoadInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fileLoadInnerPanelLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(fileLoadInnerPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(fileLoadInnerPanelLayout.createSequentialGroup()
                                                .addComponent(jRadioButtonFASTA)
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabelFastaFileStatus,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(fileLoadInnerPanelLayout.createSequentialGroup()
                                                .addGroup(fileLoadInnerPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addGroup(fileLoadInnerPanelLayout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addGroup(fileLoadInnerPanelLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel3)
                                                                        .addGroup(fileLoadInnerPanelLayout
                                                                                .createSequentialGroup()
                                                                                .addComponent(jButtonLoad,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        98,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jButtonClearAllFiles,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        98,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(0, 80, Short.MAX_VALUE))
                                        .addGroup(fileLoadInnerPanelLayout.createSequentialGroup()
                                                .addComponent(jRadioButtonGFF)
                                                .addGap(48, 48, 48)
                                                .addComponent(jLabelGffFileStatus, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))));
        fileLoadInnerPanelLayout.setVerticalGroup(
                fileLoadInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fileLoadInnerPanelLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(fileLoadInnerPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButtonFASTA)
                                        .addComponent(jLabelFastaFileStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(fileLoadInnerPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButtonGFF)
                                        .addComponent(jLabelGffFileStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(fileLoadInnerPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonLoad)
                                        .addComponent(jButtonClearAllFiles))
                                .addContainerGap(31, Short.MAX_VALUE)));

        jLabelFastaFileStatus.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(fileLoadInnerPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(186, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(fileLoadInnerPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(83, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClearAllFilesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonClearAllFilesActionPerformed
        // TODO add your handling code here:
        clearAllFiles();

    }// GEN-LAST:event_jButtonClearAllFilesActionPerformed

    private void jButtonLoadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonLoadActionPerformed

        // Call loadFile method
        loadFile();

    }// GEN-LAST:event_jButtonLoadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFileSelection;
    private javax.swing.JPanel fileLoadInnerPanel;
    private javax.swing.JButton jButtonClearAllFiles;
    private javax.swing.JButton jButtonLoad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFastaFileStatus;
    private javax.swing.JLabel jLabelGffFileStatus;
    private javax.swing.JRadioButton jRadioButtonFASTA;
    private javax.swing.JRadioButton jRadioButtonGFF;
    // End of variables declaration//GEN-END:variables

    public void loadFasta() {
        jRadioButtonFASTA.setSelected(true);
        loadFile();
    }

    public void loadGff() {
        jRadioButtonGFF.setSelected(true);
        loadFile();
    }

    public void setDataManager(DataManager dataManager) {
        this.dataManager = dataManager;
    }

    public void clearAllFiles() {
        jLabelFastaFileStatus.setVisible(false);
        jLabelGffFileStatus.setVisible(false);
        jRadioButtonFASTA.setSelected(false);
        jRadioButtonGFF.setSelected(false);

        // Clear data in DataManager
        dataManager.clearData();
    }

    private void loadFile() {
        if (jRadioButtonFASTA.isSelected()) {

            // Indicate loading state
            updateLabelToLoading(jLabelFastaFileStatus);
            // Disable Load button during loading
            jButtonLoad.setEnabled(false);

            // get parent window
            Window window = SwingUtilities.getWindowAncestor(this);
            // cast to Frame
            Frame frame = (Frame) window; // Cast Window to Frame

            FileDialog fileDialog = new FileDialog(frame, "Select FASTA File", FileDialog.LOAD);
            // Update filter to accept .fasta and .fa files
            FilenameFilter filter = new FilenameFilter() {
                @Override
                public boolean accept(java.io.File dir, String name) {
                    return name.endsWith(".fasta") || name.endsWith(".fa");
                }
            };

            fileDialog.setFilenameFilter(filter);
            fileDialog.setVisible(true);

            try {

                String filepath = fileDialog.getDirectory() + fileDialog.getFile();
                File fastaFile = new File(filepath);
                Map<String, DNASequence> fastaMap = FastaParser.parseFasta(fastaFile);

                // Store in DataManager
                dataManager.setFastaData(fastaMap);

                // Update label to show the loaded file status
                updateLabelWithFileStatus(jLabelFastaFileStatus, fileDialog.getFile());

            } catch (Exception e) {
                jLabelFastaFileStatus.setText("Error loading FASTA file.");
                jLabelFastaFileStatus.setForeground(Color.RED);
                jLabelFastaFileStatus.setVisible(true);
                e.printStackTrace();
            }

            // Re-enable Load button after loading
            jButtonLoad.setEnabled(true);

        } else if (jRadioButtonGFF.isSelected()) {

            // Indicate loading state
            updateLabelToLoading(jLabelGffFileStatus);
            // Disable Load button during loading
            jButtonLoad.setEnabled(false);

            // get parent window
            Window window = SwingUtilities.getWindowAncestor(this);
            // cast to Frame
            Frame frame = (Frame) window; // Cast Window to Frame

            FileDialog fileDialog = new FileDialog(frame, "Select GFF File", FileDialog.LOAD);
            // Update filter to accept .gtf and .gff files
            FilenameFilter filter = new FilenameFilter() {
                @Override
                public boolean accept(java.io.File dir, String name) {
                    return name.endsWith(".gff");
                }
            };

            fileDialog.setFilenameFilter(filter);
            fileDialog.setVisible(true);

            try {
                String filepath = fileDialog.getDirectory() + fileDialog.getFile();
                File gffFile = new File(filepath);

                GffParser parser;

                // get correct parser based on file extension
                if (gffFile.getName().endsWith(".gtf")) {
                    parser = GffParser.getParser(2);
                    System.out.println("[LOG]: fileLoadPanel: gff2 parser loaded");
                } else {
                    parser = GffParser.getParser(3);
                }

                FeatureList gff = parser.parse(gffFile);

                // Store in DataManager
                dataManager.setGffData(gff);

                // Update label to show the loaded file status
                updateLabelWithFileStatus(jLabelGffFileStatus, fileDialog.getFile());

            } catch (Exception e) {
                jLabelGffFileStatus.setText("Error loading GFF file.");
                jLabelGffFileStatus.setForeground(Color.RED);
                jLabelGffFileStatus.setVisible(true);
                e.printStackTrace();
            }

            // Re-enable Load button after loading
            jButtonLoad.setEnabled(true);

        }
    }

    private void updateLabelWithFileStatus(JLabel jLabelFileStatus, String filename) {
        jLabelFileStatus.setText("Loaded: " + filename);
        jLabelFileStatus.setForeground(new Color(40, 167, 69));
        jLabelFileStatus.setVisible(true);
    }

    private void updateLabelToLoading(javax.swing.JLabel label) {
        label.setText("Loading...");
        label.setForeground(Color.BLACK);
        label.setVisible(true);
    }
}
