/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GVJ.gui;

import GVJ.models.DataManager;

/**
 *
 * @author mspriggs
 */
public class mainFrame extends javax.swing.JFrame {

    // Create DataManager instance
    DataManager dataManager = new DataManager();

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(mainFrame.class.getName());

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();

        fileLoadPanel2.setDataManager(dataManager); // Pass DataManager to fileLoadPanel
        basicStatistics1.setDataManager(dataManager); // Pass DataManager to basicStatistics panel

        // Disable the Basic Statistics tab until data is loaded
        jTabbedPane.setEnabledAt(1, false);

        // Use a timer to periodically check if data is loaded
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            if (dataManager.hasFastaData() && dataManager.hasGffData()) {
                jTabbedPane.setEnabledAt(1, true);

            } else {
                // close tab and disable
                jTabbedPane.setSelectedIndex(0);
                jTabbedPane.setEnabledAt(1, false);
            }
        });
        timer.start();

        /*
         * ###########################
         * TESTING ONLY - DELETE LATER
         * ###########################
         */
        // wait 20 seconds then enable tab
        // new java.util.Timer().schedule(new java.util.TimerTask() {
        // @Override
        // public void run() {
        // jTabbedPane.setEnabledAt(1, true);
        // basicStatistics1.refreshComboBoxs();
        // }
        // }, 20000);

        /*
         * ###########################
         * TESTING ONLY - DELETE LATER
         * ###########################
         */

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        fileLoadPanel2 = new GVJ.gui.fileLoadPanel();
        sequenceViewer1 = new GVJ.gui.SequenceViewer();
        basicStatistics1 = new GVJ.gui.basicStatistics();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemImportFASTA = new javax.swing.JMenuItem();
        jMenuItemImportGFF = new javax.swing.JMenuItem();
        jMenuItemClearAllFiles = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane.setToolTipText("");
        jTabbedPane.setName(""); // NOI18N
        jTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPaneStateChanged(evt);
            }
        });
        jTabbedPane.addTab("File Selection", fileLoadPanel2);

        javax.swing.GroupLayout sequenceViewer1Layout = new javax.swing.GroupLayout(sequenceViewer1);
        sequenceViewer1.setLayout(sequenceViewer1Layout);
        sequenceViewer1Layout.setHorizontalGroup(
                sequenceViewer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                sequenceViewer1Layout.createSequentialGroup()
                                        .addContainerGap(38, Short.MAX_VALUE)
                                        .addComponent(basicStatistics1, javax.swing.GroupLayout.PREFERRED_SIZE, 700,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)));
        sequenceViewer1Layout.setVerticalGroup(
                sequenceViewer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sequenceViewer1Layout
                                .createSequentialGroup()
                                .addContainerGap(22, Short.MAX_VALUE)
                                .addComponent(basicStatistics1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)));

        jTabbedPane.addTab("Basic Statistics", sequenceViewer1);

        jMenu1.setText("File");

        jMenuItemImportFASTA.setText("Import FASTA");
        jMenuItemImportFASTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportFASTAActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemImportFASTA);

        jMenuItemImportGFF.setText("Import GFF");
        jMenuItemImportGFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportGFFActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemImportGFF);

        jMenuItemClearAllFiles.setText("Clear all files");
        jMenuItemClearAllFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClearAllFilesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemClearAllFiles);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 455,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(13, Short.MAX_VALUE)));

        jTabbedPane.getAccessibleContext().setAccessibleName("File Selection");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_jTabbedPaneStateChanged
        int selectedIndex = jTabbedPane.getSelectedIndex();
        if (selectedIndex == 1) { // Basic Statistics tab
            basicStatistics1.refreshComboBoxs(); // GFF and FASTA data may have changed
            basicStatistics1.refreshFASTAStats(); // Update FASTA statistics display
        }
    }// GEN-LAST:event_jTabbedPaneStateChanged

    private void jMenuItemImportGFFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItemImportGFFActionPerformed
        // TODO add your handling code here:
        this.fileLoadPanel2.loadGff();
    }// GEN-LAST:event_jMenuItemImportGFFActionPerformed

    private void jMenuItemClearAllFilesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItemClearAllFilesActionPerformed
        // TODO add your handling code here:
        this.fileLoadPanel2.clearAllFiles();
    }// GEN-LAST:event_jMenuItemClearAllFilesActionPerformed

    private void jMenuItemImportFASTAActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItemImportFASTAActionPerformed
        // mainFrame just asks fileLoadPanel to do something
        this.fileLoadPanel2.loadFasta();
    }// GEN-LAST:event_jMenuItemImportFASTAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GVJ.gui.basicStatistics basicStatistics1;
    private GVJ.gui.fileLoadPanel fileLoadPanel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemClearAllFiles;
    private javax.swing.JMenuItem jMenuItemImportFASTA;
    private javax.swing.JMenuItem jMenuItemImportGFF;
    private javax.swing.JTabbedPane jTabbedPane;
    private GVJ.gui.SequenceViewer sequenceViewer1;
    // End of variables declaration//GEN-END:variables
}
