/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GVJ.app;

/**
 *
 * @author mspriggs
 */
public class fileLoadPanel extends javax.swing.JPanel {

    /**
     * Creates new form fileLoadPanel
     */
    public fileLoadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroupFileSelection = new javax.swing.ButtonGroup();
        fileLoadInnerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonFASTA = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonGFF = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonLoad = new javax.swing.JButton();
        jButtonClearAllFiles = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        fileLoadInnerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "File Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel2.setText("Choose a file type to load:");

        buttonGroupFileSelection.add(jRadioButtonFASTA);
        jRadioButtonFASTA.setText("FASTA");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 11)); // NOI18N
        jLabel3.setText("(.fa, .fasta)");

        buttonGroupFileSelection.add(jRadioButtonGFF);
        jRadioButtonGFF.setText("GFF");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 11)); // NOI18N
        jLabel4.setText("(.gtf, .gff)");

        jButtonLoad.setText("Load");

        jButtonClearAllFiles.setText("Clear all");

        javax.swing.GroupLayout fileLoadInnerPanelLayout = new javax.swing.GroupLayout(fileLoadInnerPanel);
        fileLoadInnerPanel.setLayout(fileLoadInnerPanelLayout);
        fileLoadInnerPanelLayout.setHorizontalGroup(
            fileLoadInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileLoadInnerPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(fileLoadInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonGFF)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonFASTA)
                    .addGroup(fileLoadInnerPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(fileLoadInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(fileLoadInnerPanelLayout.createSequentialGroup()
                                .addComponent(jButtonLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonClearAllFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        fileLoadInnerPanelLayout.setVerticalGroup(
            fileLoadInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileLoadInnerPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonFASTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonGFF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(fileLoadInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLoad)
                    .addComponent(jButtonClearAllFiles))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(fileLoadInnerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(fileLoadInnerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFileSelection;
    private javax.swing.JPanel fileLoadInnerPanel;
    private javax.swing.JButton jButtonClearAllFiles;
    private javax.swing.JButton jButtonLoad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButtonFASTA;
    private javax.swing.JRadioButton jRadioButtonGFF;
    // End of variables declaration//GEN-END:variables
}
